/**
 * Test Spec Generator — Stage 3 (Build)
 *
 * Generates unit test specifications for Logic Apps Standard workflows.
 *
 * Produces two outputs:
 *   1. A JSON test spec in the Logic Apps unit test format
 *      (compatible with the logicapps-unittest-custom-agent pattern)
 *   2. A C# MSTest scaffold file that can be run against deployed workflows
 *
 * Test spec format (JSON):
 *   - testSuite: collection of named test cases
 *   - Each test case: mockInputs + expectedOutputs + assertions
 *
 * Test coverage strategy:
 *   - Happy path: trigger fires, all steps succeed
 *   - Error path: trigger fires, a step fails → error handler activates
 *   - Routing: one test per branch of route/condition steps
 *   - Retry: if retry policy defined, test that retry attempts are made
 *
 * Reference: wsilveiranz/logicapps-unittest-custom-agent
 */

import type { IntegrationIntent, IntegrationStep } from '../shared/integration-intent.js';
import type { MigrationPlan } from '../types/migration.js';

// ─── Test spec types ──────────────────────────────────────────────────────────

export interface TestCase {
  name:        string;
  description: string;
  trigger:     Record<string, unknown>;
  mocks:       TestMock[];
  assertions:  TestAssertion[];
}

export interface TestMock {
  /** Action name in the workflow to mock */
  actionName: string;
  /** Mocked response that the action will return */
  outputs: Record<string, unknown>;
  /** Whether to simulate failure for this action */
  failAction?: boolean;
  statusCode?: number;
}

export interface TestAssertion {
  /** WDL expression to evaluate */
  expression: string;
  /** Expected value */
  expectedValue: unknown;
  message: string;
}

export interface WorkflowTestSpec {
  workflowName: string;
  testCases:    TestCase[];
}

// ─── Main Entry Points ────────────────────────────────────────────────────────

export function generateTestSpec(
  intent: IntegrationIntent,
  workflowName: string
): WorkflowTestSpec {
  const testCases: TestCase[] = [];

  // Always generate a happy-path test
  testCases.push(buildHappyPathTest(intent, workflowName));

  // Generate error path test if error handling is non-trivial
  if (intent.errorHandling.strategy !== 'ignore') {
    testCases.push(buildErrorPathTest(intent, workflowName));
  }

  // Generate routing tests for route/condition steps
  for (const step of intent.steps) {
    if (step.type === 'route' || step.type === 'condition') {
      const routeTests = buildRoutingTests(step, intent, workflowName);
      testCases.push(...routeTests);
    }
  }

  // Generate retry test if retry policy exists
  if (intent.errorHandling.retryPolicy) {
    testCases.push(buildRetryTest(intent, workflowName));
  }

  return { workflowName, testCases };
}

/**
 * Generates a C# MSTest class that can be run against a deployed Logic Apps workflow.
 */
export function generateMsTestScaffold(
  spec: WorkflowTestSpec,
  logicAppName: string,
  subscriptionId: string = '{subscriptionId}',
  resourceGroupName: string = '{resourceGroupName}'
): string {
  const className   = sanitizeClassName(spec.workflowName) + 'Tests';
  const testMethods = spec.testCases.map(tc => buildTestMethod(tc, spec.workflowName)).join('\n\n');

  return [
    `using System;`,
    `using System.Net.Http;`,
    `using System.Text;`,
    `using System.Text.Json;`,
    `using System.Threading.Tasks;`,
    `using Microsoft.VisualStudio.TestTools.UnitTesting;`,
    ``,
    `/// <summary>`,
    `/// MSTest unit tests for Logic Apps workflow: ${spec.workflowName}`,
    `/// Generated by BizTalk to Logic Apps Migration Tool`,
    `/// Generated: ${new Date().toISOString()}`,
    `///`,
    `/// Prerequisites:`,
    `///   1. Deploy the Logic Apps Standard app to Azure`,
    `///   2. Set TEST_LOGIC_APP_NAME environment variable`,
    `///   3. Set TEST_AZURE_SUBSCRIPTION_ID environment variable`,
    `///   4. Set TEST_RESOURCE_GROUP_NAME environment variable`,
    `///   5. Authenticate: az login or managed identity`,
    `/// </summary>`,
    `[TestClass]`,
    `public class ${className}`,
    `{`,
    `    private static HttpClient _httpClient = new HttpClient();`,
    `    private static string _logicAppName    = Environment.GetEnvironmentVariable("TEST_LOGIC_APP_NAME")    ?? "${logicAppName}";`,
    `    private static string _subscriptionId  = Environment.GetEnvironmentVariable("TEST_AZURE_SUBSCRIPTION_ID") ?? "${subscriptionId}";`,
    `    private static string _resourceGroup   = Environment.GetEnvironmentVariable("TEST_RESOURCE_GROUP_NAME")  ?? "${resourceGroupName}";`,
    ``,
    `    private string RunUrl => $"https://management.azure.com/subscriptions/{_subscriptionId}" +`,
    `        $"/resourceGroups/{_resourceGroup}/providers/Microsoft.Web/sites/{_logicAppName}" +`,
    `        $"/hostruntime/runtime/webhooks/workflow/api/management/workflows/${spec.workflowName}" +`,
    `        "/triggers/trigger/run?api-version=2022-03-01";`,
    ``,
    testMethods,
    ``,
    `    private async Task<(int StatusCode, string Body)> TriggerWorkflow(object payload)`,
    `    {`,
    `        var json    = JsonSerializer.Serialize(payload);`,
    `        var content = new StringContent(json, Encoding.UTF8, "application/json");`,
    `        var resp    = await _httpClient.PostAsync(RunUrl, content);`,
    `        var body    = await resp.Content.ReadAsStringAsync();`,
    `        return ((int)resp.StatusCode, body);`,
    `    }`,
    `}`,
  ].join('\n');
}

// ─── Test Case Builders ───────────────────────────────────────────────────────

function buildHappyPathTest(
  intent: IntegrationIntent,
  workflowName: string
): TestCase {
  const mocks: TestMock[] = [];

  // Mock each send/enrich step to return success
  for (const step of intent.steps) {
    if (step.type === 'send' || step.type === 'enrich' || step.type === 'invoke-function') {
      mocks.push({
        actionName:  sanitizeActionName(step.description),
        statusCode:  200,
        outputs:     { body: { status: 'success' }, statusCode: 200 },
      });
    }
  }

  return {
    name:        `${workflowName}_HappyPath`,
    description: `Happy path: ${intent.trigger.source} triggers workflow and all steps succeed.`,
    trigger:     buildTriggerPayload(intent),
    mocks,
    assertions: [
      {
        expression:    "@outputs('trigger')?['statusCode']",
        expectedValue: 202,
        message:       'Workflow should be accepted (202) on valid trigger',
      },
    ],
  };
}

function buildErrorPathTest(
  intent: IntegrationIntent,
  workflowName: string
): TestCase {
  const sendSteps = intent.steps.filter(
    s => s.type === 'send' || s.type === 'enrich' || s.type === 'invoke-function'
  );

  const mocks: TestMock[] = sendSteps.map((step, idx) => ({
    actionName:  sanitizeActionName(step.description),
    statusCode:  idx === 0 ? 500 : 200,  // First send fails
    outputs:     idx === 0
      ? { statusCode: 500, body: { error: 'Internal Server Error' } }
      : { statusCode: 200 },
    failAction:  idx === 0,
  }));

  const assertions: TestAssertion[] = [
    {
      expression:    "@result('Scope_Main')?[0]?['status']",
      expectedValue: 'Failed',
      message:       'Main scope should show Failed status when a step errors',
    },
  ];

  if (intent.errorHandling.deadLetterTarget) {
    assertions.push({
      expression:    "@result('Send_To_Dead_Letter_Queue')?[0]?['status']",
      expectedValue: 'Succeeded',
      message:       'Dead-letter action should succeed after main failure',
    });
  }

  return {
    name:        `${workflowName}_ErrorPath`,
    description: `Error path: first send step fails, error handler activates.`,
    trigger:     buildTriggerPayload(intent),
    mocks,
    assertions,
  };
}

function buildRoutingTests(
  step: IntegrationStep,
  intent: IntegrationIntent,
  workflowName: string
): TestCase[] {
  const tests: TestCase[] = [];
  const b = step.branches;

  if (!b) return tests;

  // True branch test
  if (b.trueBranch && b.trueBranch.length > 0) {
    tests.push({
      name:        `${workflowName}_Route_TrueBranch_${sanitizeActionName(step.description)}`,
      description: `Routing test: condition evaluates to true, true branch executes.`,
      trigger:     buildTriggerPayload(intent, { routeCondition: 'true' }),
      mocks:       [],
      assertions: [{
        expression:    `@result('${sanitizeActionName(b.trueBranch[0]?.description ?? '')}')?[0]?['status']`,
        expectedValue: 'Succeeded',
        message:       'True branch should execute when condition is true',
      }],
    });
  }

  // False branch test
  if (b.falseBranch && b.falseBranch.length > 0) {
    tests.push({
      name:        `${workflowName}_Route_FalseBranch_${sanitizeActionName(step.description)}`,
      description: `Routing test: condition evaluates to false, else branch executes.`,
      trigger:     buildTriggerPayload(intent, { routeCondition: 'false' }),
      mocks:       [],
      assertions: [{
        expression:    `@result('${sanitizeActionName(b.falseBranch[0]?.description ?? '')}')?[0]?['status']`,
        expectedValue: 'Succeeded',
        message:       'False branch should execute when condition is false',
      }],
    });
  }

  // Switch case tests
  if (b.cases) {
    for (const c of b.cases) {
      tests.push({
        name:        `${workflowName}_Route_Case_${sanitizeActionName(c.value)}`,
        description: `Routing test: switch expression matches case "${c.value}".`,
        trigger:     buildTriggerPayload(intent, { routeValue: c.value }),
        mocks:       [],
        assertions: c.steps.length > 0 ? [{
          expression:    `@result('${sanitizeActionName(c.steps[0]?.description ?? '')}')?[0]?['status']`,
          expectedValue: 'Succeeded',
          message:       `Case "${c.value}" branch should execute when expression matches`,
        }] : [],
      });
    }
  }

  return tests;
}

function buildRetryTest(
  intent: IntegrationIntent,
  workflowName: string
): TestCase {
  const rp = intent.errorHandling.retryPolicy!;
  const sendStep = intent.steps.find(s => s.type === 'send' || s.type === 'invoke-function');

  return {
    name:        `${workflowName}_RetryPolicy`,
    description: `Retry policy test: send step fails ${rp.count} times then succeeds.`,
    trigger:     buildTriggerPayload(intent),
    mocks:       sendStep ? [
      // Simulate failure on first attempt, success on subsequent
      {
        actionName: sanitizeActionName(sendStep.description),
        outputs:    { statusCode: 503, body: 'Service Unavailable' },
        failAction: true,
        statusCode: 503,
      },
    ] : [],
    assertions: [
      {
        expression:    "@outputs('trigger')?['statusCode']",
        expectedValue: 202,
        message:       `Workflow should eventually succeed after ${rp.count} retry attempt(s)`,
      },
    ],
  };
}

// ─── MSTest Method Builder ────────────────────────────────────────────────────

function buildTestMethod(tc: TestCase, workflowName: string): string {
  const methodName = sanitizeClassName(tc.name);
  const payload    = JSON.stringify(tc.trigger, null, 4)
    .split('\n').map((l, i) => i === 0 ? l : `        ${l}`).join('\n');

  const assertLines = tc.assertions.map(a =>
    `        // ${a.message}\n        // Assert: ${a.expression} == ${JSON.stringify(a.expectedValue)}`
  ).join('\n');

  return [
    `    [TestMethod]`,
    `    [Description("${tc.description}")]`,
    `    public async Task ${methodName}()`,
    `    {`,
    `        // Arrange`,
    `        var payload = ${payload};`,
    ``,
    `        // Act`,
    `        var (statusCode, responseBody) = await TriggerWorkflow(payload);`,
    ``,
    `        // Assert`,
    `        Assert.IsTrue(statusCode is 200 or 202, $"Expected 200/202 but got {statusCode}. Body: {responseBody}");`,
    assertLines,
    `    }`,
  ].join('\n');
}

// ─── Trigger Payload Builder ──────────────────────────────────────────────────

function buildTriggerPayload(
  intent: IntegrationIntent,
  overrides: Record<string, unknown> = {}
): Record<string, unknown> {
  const basePayload: Record<string, unknown> = {
    messageType: intent.dataFormats.input,
    source:      intent.trigger.source,
    timestamp:   new Date().toISOString(),
  };

  // Add schema-driven sample data
  if (intent.dataFormats.input === 'xml') {
    basePayload['body'] = `<Root><TODO>sample XML matching source schema</TODO></Root>`;
  } else if (intent.dataFormats.input === 'json') {
    basePayload['body'] = { TODO: 'sample JSON matching source schema' };
  }

  return { ...basePayload, ...overrides };
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function sanitizeActionName(description: string): string {
  return description
    .replace(/[^a-zA-Z0-9\s_-]/g, '')
    .trim()
    .split(/[\s_-]+/)
    .filter(w => w.length > 0)
    .slice(0, 4)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('_');
}

function sanitizeClassName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^[0-9]/, '_$&');
}
