using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// MSTest unit tests for Logic Apps workflow: Orchestration_1
/// Generated by BizTalk to Logic Apps Migration Tool
/// Generated: 2026-02-28T21:57:22.590Z
///
/// Prerequisites:
///   1. Deploy the Logic Apps Standard app to Azure
///   2. Set TEST_LOGIC_APP_NAME environment variable
///   3. Set TEST_AZURE_SUBSCRIPTION_ID environment variable
///   4. Set TEST_RESOURCE_GROUP_NAME environment variable
///   5. Authenticate: az login or managed identity
/// </summary>
[TestClass]
public class Orchestration_1Tests
{
    private static HttpClient _httpClient = new HttpClient();
    private static string _logicAppName    = Environment.GetEnvironmentVariable("TEST_LOGIC_APP_NAME")    ?? "WhileLoopComplex";
    private static string _subscriptionId  = Environment.GetEnvironmentVariable("TEST_AZURE_SUBSCRIPTION_ID") ?? "{subscriptionId}";
    private static string _resourceGroup   = Environment.GetEnvironmentVariable("TEST_RESOURCE_GROUP_NAME")  ?? "{resourceGroupName}";

    private string RunUrl => $"https://management.azure.com/subscriptions/{_subscriptionId}" +
        $"/resourceGroups/{_resourceGroup}/providers/Microsoft.Web/sites/{_logicAppName}" +
        $"/hostruntime/runtime/webhooks/workflow/api/management/workflows/Orchestration_1" +
        "/triggers/trigger/run?api-version=2022-03-01";

    [TestMethod]
    [Description("Happy path: Unknown — no activating receive shape found triggers workflow and all steps succeed.")]
    public async Task Orchestration_1_HappyPath()
    {
        // Arrange
        var payload = {
            "messageType": "xml",
            "source": "Unknown — no activating receive shape found",
            "timestamp": "2026-02-28T21:57:22.589Z",
            "body": "<Root><TODO>sample XML matching source schema</TODO></Root>"
        };

        // Act
        var (statusCode, responseBody) = await TriggerWorkflow(payload);

        // Assert
        Assert.IsTrue(statusCode is 200 or 202, $"Expected 200/202 but got {statusCode}. Body: {responseBody}");
        // Workflow should be accepted (202) on valid trigger
        // Assert: @outputs('trigger')?['statusCode'] == 202
    }

    [TestMethod]
    [Description("Error path: first send step fails, error handler activates.")]
    public async Task Orchestration_1_ErrorPath()
    {
        // Arrange
        var payload = {
            "messageType": "xml",
            "source": "Unknown — no activating receive shape found",
            "timestamp": "2026-02-28T21:57:22.590Z",
            "body": "<Root><TODO>sample XML matching source schema</TODO></Root>"
        };

        // Act
        var (statusCode, responseBody) = await TriggerWorkflow(payload);

        // Assert
        Assert.IsTrue(statusCode is 200 or 202, $"Expected 200/202 but got {statusCode}. Body: {responseBody}");
        // Main scope should show Failed status when a step errors
        // Assert: @result('Scope_Main')?[0]?['status'] == "Failed"
    }

    [TestMethod]
    [Description("Retry policy test: send step fails 3 times then succeeds.")]
    public async Task Orchestration_1_RetryPolicy()
    {
        // Arrange
        var payload = {
            "messageType": "xml",
            "source": "Unknown — no activating receive shape found",
            "timestamp": "2026-02-28T21:57:22.590Z",
            "body": "<Root><TODO>sample XML matching source schema</TODO></Root>"
        };

        // Act
        var (statusCode, responseBody) = await TriggerWorkflow(payload);

        // Assert
        Assert.IsTrue(statusCode is 200 or 202, $"Expected 200/202 but got {statusCode}. Body: {responseBody}");
        // Workflow should eventually succeed after 3 retry attempt(s)
        // Assert: @outputs('trigger')?['statusCode'] == 202
    }

    private async Task<(int StatusCode, string Body)> TriggerWorkflow(object payload)
    {
        var json    = JsonSerializer.Serialize(payload);
        var content = new StringContent(json, Encoding.UTF8, "application/json");
        var resp    = await _httpClient.PostAsync(RunUrl, content);
        var body    = await resp.Content.ReadAsStringAsync();
        return ((int)resp.StatusCode, body);
    }
}